name: 'Semver tags'
description: 'Gets the previous semver tag and calculates the next version. Optionally apply the version as a new tag.'
inputs:
  GITHUB_TOKEN:
    description: The github token.
    required: true
  version-prefix:
    description: 'A value prefixed to the version number.'
    required: false
    default: ''
  incremented-value:
    description: 'What value should be incremented?'
    required: true
    default: patch
  prerelease:
    description: 'The prerelease tag to use.'
    required: false
  metadata:
    description: 'The metadata to use.'
    required: false
  dry-run:
    description: 'Performs a version calculation without committing a tag.'
    required: false
    default: false
outputs:
  semantic-version:
    description: 'The calculated version number.'
  core-version: 
    description: 'The core version part of the semantic version.'
  previous-version:
    description: 'The previous version number.'
runs:
  using: 'node12'
  main: 'dist/index.js'
