name: 'Semver tags'
description: 'Gets the previous semver tag and calculates the next version. Optionally apply the version as a new tag.'
branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: The github token.
    required: true
  tag-prefix:
    description: 'A value prefixed to the version number when tagging the repo.'
    required: false
    default: ''
  default-version:
    description: 'The version number that will be used if no semver tag is found.'
    required: false
    default: '1.0.0'
  incremented-value:
    description: 'What value should be incremented?'
    required: false
    default: patch
  prerelease:
    description: 'The prerelease tag to use.'
    required: false
  metadata:
    description: 'The metadata to use.'
    required: false
  add-minor-tag:
    description: 'Adds/updates a tag for the major.minor version if the semver version is not a prerelease.'
    required: false
    default: false
  add-major-tag:
    description: 'Adds/updates a tag for the major version if the semver version is not a prerelease.'
    required: false
    default: false
  dry-run:
    description: 'Performs a version calculation without committing a tag.'
    required: false
    default: false
outputs:
  semantic-version:
    description: 'The calculated version number.'
  core-version: 
    description: 'The core version part of the semantic version.'
  previous-version:
    description: 'The previous version number.'
runs:
  using: 'node12'
  main: 'dist/index.js'
