name: 'Semver tags'
description: 'Gets the previous semver tag and calculates the next version. Optionally apply the version as a new tag.'
inputs:
  GITHUB_TOKEN:
    description: The github token.
    required: true
  version-prefix:
    description: 'A value prefixed to the version number.'
    required: false
    default: ''
outputs:
  version:
    description: 'The calculated version number.'
  previousVersion:
    description: 'The previous version number.'
runs:
  using: 'node12'
  main: 'dist/index.js'
